# -*- coding: utf-8 -*-
"""Image Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107GrQw6JkJW5HaXjNSUmmYNPgyzJrsU8
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
import requests

model = MobileNetV2(weights='imagenet')

url = "https://raw.githubusercontent.com/pytorch/hub/master/images/dog.jpg"
img_path = tf.keras.utils.get_file("sample.jpg", url)

def predict_image(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)

    preds = model.predict(img_array)
    decoded = decode_predictions(preds, top=3)[0]

    plt.imshow(img)
    plt.axis('off')
    plt.show()

    print("\nTop Predictions:")
    for i, (_, name, score) in enumerate(decoded):
        print(f"{i+1}. {name} → {score:.4f}")

predict_image(img_path)